import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TeleHealth",
  description: "Generated by TeleHealth",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* n8n chat CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@n8n/chat/dist/style.css"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Container for the chat */}
        <div id="n8n-chat-container"></div>

        {/* ES Module version of n8n chat */}
        <script
          type="module"
          dangerouslySetInnerHTML={{
            __html: `
              import { createChat } from 'https://cdn.jsdelivr.net/npm/@n8n/chat/dist/chat.bundle.es.js';

              createChat({
                container: '#n8n-chat-container',
                webhookUrl: 'https://eaglee.app.n8n.cloud/webhook/e75c4098-f321-46b6-8499-8c7f514f14ec/chat'
              });
            `,
          }}
        />
      </body>
    </html>
  );
}
